export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const HTTP_METHODS = {
  OPTIONS: 'OPTIONS',
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH',
} as const;

export const HEADERS = {
  CORRELATION_ID: 'x-fxg-correlation-id',
  API_ACCESS_TOKEN: 'api-access-token',
  AUTHORIZATION: 'authorization',
} as const;

export const RESPONSES = {
  SUCCESS: HTTP_STATUS_CODES.OK,
  BADREQUEST: HTTP_STATUS_CODES.BAD_REQUEST,
  TOOMANYREQ: HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
} as const;
